In [1]:
import os
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

In [27]:
dataset_zip = np.load(os.getcwd() + '/source/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz', 
                      allow_pickle=True,
                      encoding='bytes'
                     )
type(dataset_zip)

numpy.lib.npyio.NpzFile

In [29]:
print(list(dataset_zip.keys()))

['metadata', 'imgs', 'latents_classes', 'latents_values']


In [30]:
imgs = dataset_zip['imgs']
print(type(imgs))

<class 'numpy.ndarray'>


In [31]:
imgs.shape

(737280, 64, 64)

In [32]:
latents_values = dataset_zip['latents_values']
latents_values.shape

(737280, 6)

In [33]:
latents_values[100]

array([1.        , 1.        , 0.5       , 0.        , 0.09677419,
       0.12903226])

In [34]:
latents_classes = dataset_zip['latents_classes']
latents_classes.shape

(737280, 6)

In [35]:
latents_classes[1500]

array([ 0,  0,  0,  1, 14, 28])

In [39]:
metadata = dataset_zip['metadata'][()]

In [40]:
type(metadata)

dict

In [43]:
list(metadata.keys())

[b'date',
 b'description',
 b'version',
 b'latents_names',
 b'latents_possible_values',
 b'latents_sizes',
 b'author',
 b'title']

In [47]:
latents_sizes = metadata[b'latents_sizes']
latents_sizes

array([ 1,  3,  6, 40, 32, 32])

In [48]:
latents_bases = np.concatenate((latents_sizes[::-1].cumprod()[::-1][1:], np.array([1,])))
latents_bases

array([737280, 245760,  40960,   1024,     32,      1])

In [49]:
latents_sizes[::-1].cumprod()

array([    32,   1024,  40960, 245760, 737280, 737280])

In [50]:
latents_sizes[::-1].cumprod()[::-1]

array([737280, 737280, 245760,  40960,   1024,     32])